<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Yichen Lu</title>
    <link rel="stylesheet" href="css/long-scrolly.css">
    <link rel="stylesheet" href="css/styles.css">
    <link rel="stylesheet" type="text/css" href="plugins/css/default.css" />
    <link rel="stylesheet" type="text/css" href="plugins/css/component.css" />
    <link href="https://fonts.googleapis.com/css?family=Comfortaa:400,300,700" rel="stylesheet">
</head>

<body>

    <!-- Navigation -->
    <nav class="main-menu">

        <ul>
            <li id="brand"><a href="./"><h1>Yichen Lu</h1></a></li>
            <li><a href="./">Home</a></li>
            <li><a href="portfolio.php">Portfolio</a></li>
            <li><a href="contacts.php">Contact</a></li>
        </ul>
    </nav>